# module2: LeNet

feature_extractor:

  conv1:
    in_channels: 1
    out_channels: 6
    kernel_size: 5
    stride: 1
    padding: 0
    dilation: 1

  pool1:
    kernel_size: 2
    stride: 2
    padding: 0
    dilation: 1

  conv2:
    in_channels: 6
    out_channels: 16
    kernel_size: 5
    stride: 1
    padding: 0
    dilation: 1

  pool2:
    kernel_size: 2
    stride: 2
    padding: 0
    dilation: 1

images_classifier:

  input_dim: 256
  output_dim: 10

  mid_dim_1: 120
  mid_dim_2: 84
